name: Perueiro Platform + App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true # Define se outros workflows em andamento s√£o cancelados ou n√£o

jobs:
  # -----------------------------
  # 1Ô∏è‚É£ BUILD DO APLICATIVO ANDROID
  # -----------------------------
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # Cloudflare R2
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
      R2_PUBLIC_BASE_URL: ${{ secrets.R2_PUBLIC_BASE_URL }}
      R2_REGION: ${{ secrets.R2_REGION }}

      # Web
      NEXT_PUBLIC_R2_BASE: ${{ secrets.NEXT_PUBLIC_R2_BASE }}
      NEXT_PUBLIC_R2_BUCKET: ${{ secrets.NEXT_PUBLIC_R2_BUCKET }}

    steps:
      - name: ‚¨áÔ∏è Checkout
        uses: actions/checkout@v4

      # -------------------------
      # WEB BUILD + DEPLOY
      # -------------------------
      - name: üì¶ Install dependencies
        run: npm ci

      - name: üèóÔ∏è Build Web
        run: npm run build

      - name: üöÄ Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_WATER_08508BA0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          output_location: ".next"
